### ISSUE TITLE
Function for constructing triples in expressions

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-star#109]
We may think about defining a built-in function that enables users to construct triples in expressions. Such a function may be used in BIND, but also in FILTER and in SELECT.

**Comment by afs** [comment]
ARQ supports 5 functions related to embedded triples. Currently 
[they have URIs](https://jena.apache.org/documentation/rdfstar/#sparql-functions-related-to-triple-terms)
and implemented as custom functions but, like the constructors and accessors for other RDF terms in SPARQL they ough tto have keywords:

Function | Description
-- | --
triple(?s, ?p, ?o) | Create a triple term from s/p/o
isTriple(?t) | Return true if the argument value is a triple term else false
subject(?t) | Return the subject of the triple term (else error)
predicate(?t) | Return the predicate (property) of the triple term (else error)
object(?t) | Return the object of the triple term  (else error)

**Comment by hartig** [comment]
@jeenbroekstra do you have such functions in the SPARQL-star support in RDF4J? What do they look like? 

@klinovp what about Stardog?

@gkellogg ?

**Comment by gkellogg** [comment]
I have implemented no such functions, but they make sense.

**Comment by afs** [comment]
Issue #27 has responses from implementers about constructors and accessors.

**Comment by hartig** [comment]
Good find. I thought I had seen such a discussion before ;-)

**Comment by jeenbroekstra** [comment]
@hartig RDF4J has the same functions as mentioned for GraphDB by @VladimirAlexiev in #27. And I agree that a standardization (including a better namespace) would be useful.

**Comment by afs** [comment]
(ses also #6)

Related to this issues, should `<<?s ?p ?o>>` be allowed in expressions (FILTER, BIND SELECT-AS).

I've checked and it can be done. Add it to `PrimaryExpression`. There are some details of defining evaluation because it may have variables inside an element of `PrimaryExpression`.

However, it does not add any new functionality as far as I can see over TRIPLE, and TRIPLE is more general (it can take expressions for arguments, pattern syntax `<<?s ?p ?o>>` doesn't. 

If `<<>>` is syntactic sugar - is it worth the effort, including support and education implications.

Nearby: SPARQL does not allow variables in parts of literals: e.g. `?lex^^xsd:date, `?str@?lang`. It has been suggested to add it to patterns. It is not new functionality: using `lang` or `datatype` or `str`(+`isLiteral`) has the same effect.

**Comment by hartig** [comment]
During today's telco we have agreed to implement this proposal. I will create a PR for it.

**Comment by hartig** [comment]
PR #118 implements the proposal to add the five new built-in functions to the spec.

**Comment by hartig** [comment]
Closing this issue as PR #118 has been merged now.
