### ISSUE TITLE
align the Semantics test suite with the current content of the Semantics section

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#136]
as decided during call: https://w3c.github.io/rdf-star/Minutes/2021-03-19.html#t03

**Comment by pchampin** [comment]
Done in 7a0b090a

**Comment by TallTed** [comment]
I strongly advise, and request, that any substantive change (and really, every change) go through the Pull Request cycle, with at least a day (preferably 2-3 days, if not longer) between the submission/creation of each PR and the merging of that PR.

Reviewing individual commits is possible, but suggesting changes of any kind to those commits requires many more steps than suggesting a change to an in-flight PR.

**Comment by pchampin** [comment]
I didn't consider that change to be substansive, as it was merely reflecting changes in the spec that have already been discussed.

About making a PR for every possible change, I see your point about easing the process of commenting. I'll keep that in mind.

**Comment by TallTed** [comment]
To my mind, substantive changes include any that involve any rephrasing, as even a single word change can unintentionally change subjective interpretation if not objective meaning.  (This is different than consequential changes, which are *meant* to change interpretation and/or meaning.)

Discussed, decided, resolved changes, no matter how involved those processes get -- unless concluding with a resolution specifying the _exact_ phrasing to be inserted and/or removed, and *exactly* that change being made (and sometimes even with such exactitude) -- should always go through the PR process, because the specifics of those (discussions, decisions, resolutions) can easily be understood differently by each participant, particularly including the Editor who goes forth to act on the will of the group -- and again, it's far easier to fix such differences through a PR cycle (and possibly revisited discussion, decision, resolution) than following a sudden realization during transition from CG to WG and/or CR that phrase x went against someone's understanding of resolution y.

I hope that makes sense...

**Comment by afs** [comment]
A proper review can only be done when the document is complete. Merging a PR is not final agreement.

I think we need to let the editors use their discretion and optimize their time.

**Comment by TallTed** [comment]
One of my goals is optimization of everyone's time, which I think is aided by PRs far more than by direct commits.
