### ISSUE TITLE
CG Report scope : document alternatives or only make one proposal?

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star#15]
Will the CG report include alternatives (e.g. SA vs PG and variations) or be a draft of a spec?

**Comment by pchampin** [comment]
I see it more as a draft of a spec -- while we can include some discussions in appendix, the goal is to get consensus on one syntax and semantics, to ensure interoperability across implementations.

As for SA vs PG mode, I am not a big fan of having the same syntax interpreted differently depending on some (implicit) context. I am much more in favour of two different syntactical construct, namely ``<<...>>`` for SA mode, and something in the line of the Annotation proposal in #9 for PG mode. How this would reflect in the abstract syntax is yet to be discussed...

**Comment by hartig** [comment]
I also see it more as a draft of a spec.

Regarding the question of whether the report should include alternatives (SA vs PG), I think we should define everything in a way such that it captures SA mode (i.e., in contrast to what I had done in the paper) because SA mode is less controversial. On top of that, we can add the annotation syntax (#9), which is essentially a syntactic version of PG mode. Thereafter, we can see how far we can/should push a related syntax extension into the actual formalization (or we simply leave the annotation syntax only as purely syntactic sugar).

**Comment by pchampin** [comment]
It was resolved during today's call to close this issue
https://www.w3.org/2020/11/13-rdf-star-minutes.html

and that the CG report should make only one proposal.
