### ISSUE TITLE
MIME types and file extensions 

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/rdf-star#26]
Standardize MIME types and file extensions of rdf-star and sparql-star formats.

GraphDB and rdf4j do this: https://graphdb.ontotext.com/documentation/free/devhub/rdf-sparql-star.html#mime-types-and-file-extensions-for-rdf-in-rdf4j

@klinovp what does Stardog do?

@hartig How about Blazegraph?

**Comment by klinovp** [comment]
Stardog did not yet introduce new content types. Apart of RDF* we have extensions for the SPARQL Query Results format (binary, XML, and JSON), e.g. with `statement` as a new value type (in XML and JSON). 

We don't have anything against new MIME types, we just didn't want to do any extra effort before there's some agreement on it, since it's not easy for us to break backward compatibility.

**Comment by hartig** [comment]
I don't know whether Blazegraph uses special mime types.

Anyways, I agree that the spec should introduce mime types.

**Comment by hartig** [comment]
Related to this discussion about mime types for the Turtle* and SPARQL* files, we also have to decide about mime types for the extended formats for serializing the result of a SPARQL* SELECT query. For the latter discussion, I have created a separate issue: #43

**Comment by pchampin** [comment]
See also #55

**Comment by pchampin** [comment]
This was discussed during our last call https://w3c.github.io/rdf-star/Minutes/2021-01-22.html#item03

**Comment by lisp** [comment]
one reading of the ietf registration process [1] and the iana turtle registration [2,3] is that they do not allow for the approach proposed in the last call. the w3c tag finding [4] reinforces this reading - despite that it appears to give up on the interpretation faster than it can present it.

[1] requires, in section 4.4, "Canonicalization and Format Requirements", that
     All registered media types MUST employ a single, canonical data format, regardless of registration tree.

this is followed by a passage which describes the relation between the type registration and the respective specification.

the n-triples iana registration [2] references the w3c n-triples team submission [3] as its specification.
while this should be revised to reflect the current tr and could again be revised to indicate some future tr, the current "published specification" does not describe a means to permit encoding variants.

the tag finding [4] suggests that "inconsistency between representation data and metadata is an error that should be discovered and corrected rather than silently ignored."
most of its discussion covers user agent rather than server behaviour, but for the passage describes "bad server configuration".
 
----
[1] https://tools.ietf.org/html/rfc6838  
[2] https://www.iana.org/assignments/media-types/text/turtle  
[3] http://www.w3.org/TeamSubmission/2008/SUBM-turtle-20080114/  
[4] https://www.w3.org/2001/tag/doc/mime-respect.html

**Comment by pchampin** [comment]
Closing this as duplicate, as the discussion took place in #43
