### ISSUE TITLE
SPARQL-star constructor and accessors

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/rdf-star#27]
https://graphdb.ontotext.com/documentation/free/devhub/rdf-sparql-star.html

GraphDB introduces several new SPARQL functions for manipulating embedded triples
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
    VALUES ?triple { <<:man :hasSpouse :woman>> }

    # Checks if the variable is of type embedded triple
    BIND (rdf:isTriple(?triple) as ?isTriple)

    # Extract the subject, predicate or object from an embedded triple
    BIND (rdf:subject(?triple) as ?subject)
    BIND (rdf:predicate(?triple) as ?predicate)
    BIND (rdf:object(?triple) as ?object)

    # Create a new embedded statement
    BIND (rdf:Statement(?subject, ?predicate, ?object) as ?newTriple)
}
```

I think it would be beneficial to standardize similar functions

**Comment by pchampin** [comment]
Out of curiosity: do other implementations have similar functions? @afs @klinovp @HolgerKnublauch @gkellogg

**Comment by klinovp** [comment]
yeah, Stardog has pretty much the same set of SPARQL functions, just not in the RDF namespace.

**Comment by gkellogg** [comment]
I don’t currently support such functions, but they make sense.

**Comment by afs** [comment]
Same - Apache Jena has functions for accessors etc. not in the `rdf` namespace.

My assumption has been that SPARQL-star is spec'ed out we add keywords because these are building blocks (c.f. DATATYPE)

SUBJECT, OBJECT, PREDICATE/PROPERTY, . . .


I don't think pregressign this and other SPARQL-star features is currently urgent (Jan 2021) . The current focus on getting complete documents for Turtle-start and the RDF-star semantics is a good use of time. The CG can publish these to the wider community for comment and feedback and move focus to SPARQL-star because SPARQL-star is a consequence of the fundamental design.

----

For reference: `afn` being the Jena namespace for custom functions:

Function | Description
-- | --
`afn:subject(?t)` | Return the subject of the triple term
`afn:predicate(?t)` | Return the predicate (property) of the triple term
`afn:object(?t)` | Return the object of the triple term
`afn:triple(?s, ?p, ?o)` | Create a triple term from s/p/o
`afn:isTriple(?t)`   | Return true if the argument value is a triple term

https://jena.apache.org/documentation/rdfstar/index.html

**Comment by HolgerKnublauch** [comment]
Yes we have similar functions, although more specific to our current implementation based on long URIs. http://datashapes.org/reification.html#tosh

**Comment by hartig** [comment]
PR #118 implements the proposal to add the requested functions as new built-in functions to the spec. I am closing this issue as PR #118 has been merged now.
