### ISSUE TITLE
are embedded triples asserted?

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-star#63]
It is still unclear to me whether embedded triples are also supposed
to be asserted - the initial RDF* said yes, the current document says no, some
people in the group seem to be arguing for yes.

These sorts of foundational issues need to be cleared up early.

**Comment by TallTed** [comment]
I believe the initial RDF* in the old paper should be treated as a historical relic, at this point.  That was largely an individual effort, which has served well as a starting point, spawning larger conversation among more participants, and led to the current draft which inherited much but not all from the original paper.

Consensus, from my reading of the lists and issues today, is that embedded triples are not asserted by that embedding; to be asserted requires they be instantiated outside an embed.  Else, `<< :Bob :is :stupid >> :assertedBy :Mary` is interpreted to mean `<< :Bob :is :stupid >> :assertedBy :Mary, :TallTed` even though I explicitly assert `:Bob :is :genius . << :Bob :is :genius >> :assertedBy :TallTed`.

**Comment by hartig** [comment]
@TallTed yes!

**Comment by pchampin** [comment]
The intent of PR #58 , which has been approved [during our last call][1], was indeed to clarify the situation. Now we have:

* an explicit [distinction between asserted an embedded triple][2] in the abstract syntax
* a [concrete syntax][3] to avoid redundancy when creating a triple that is both asserted and embedded (fullfilling a need that was previously addressed by PG-mode)
* an [appendix section][4] tracking the historical notions of SA-mode and PG-mode, and explaining why they are not included in the report
* a [test][5] in the test-suite  that will ensure that the formal semantics will adequately capture that (whether the formal semantics will be an extension of RDF's or based on some syntactic sugar is orrthogonal, IMO).

@pfps do you consider that the above is enough to close this issue? Otherwise, what do you think is missing?


[1]: https://w3c.github.io/rdf-star/Minutes/2020-12-11.html#item05
[2]: https://w3c.github.io/rdf-star/rdf-star-cg-spec.html#dfn-embedded
[3]: https://w3c.github.io/rdf-star/rdf-star-cg-spec.html#grammar-production-objectList
[4]:https://w3c.github.io/rdf-star/rdf-star-cg-spec.html#sa-mode-and-pg-mode
[5]: https://w3c.github.io/rdf-star/tests/semantics/manifest#embedded-not-asserted

**Comment by josd** [comment]
Nice progress and implementing this in EYE worked well. The above non entailment test works as well
```
$ eye --quiet --nope https://w3c.github.io/rdf-star/tests/semantics/test002a.ttl --not-entail https://w3c.github.io/rdf-star/tests/semantics/test002pgr.ttl

PREFIX : <http://example.com/ns#>

true.
```

**Comment by pchampin** [comment]
gentle reminder of https://github.com/w3c/rdf-star/issues/63#issuecomment-743730329
> @pfps do you consider that the above is enough to close this issue? Otherwise, what do you think is missing?

**Comment by pfps** [comment]
The situation is different now, with the possible extra syntax for PR mode, but the situation is adequately clear.

**Comment by pchampin** [comment]
Ok, thanks
