### ISSUE TITLE
are embedded triples unique?

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-star#64]
The uniqueness of
embedded triples does not appear to me to be determined - the initial RDF* and
the current documents say yes in their formal sections but central examples
have fatal flaws if embedded triples are unique.

These foundational issues should be cleared up early.

**Comment by TallTed** [comment]
The meaning of your title is not obvious to people not versed in some discipline, in which I am also not versed so cannot even name.

I have come to understand your title means "Do embedded triples always have the same meaning?" i.e., "Does each embedded triple lexical have a singular meaning, across all instances of that triple lexical, regardless of graph, embeddedness, etc?"

I think the answer is "Yes, unless blank nodes are involved; then, the answer is indeterminate."

**Comment by pchampin** [comment]
I didn't want to pollute this discussion with a looong comment, but FTR
> central examples have fatal flaws if embedded triples are unique

I explained in details on the mailing list why I think said examples are imperfect, but not fatally flawed
https://lists.w3.org/Archives/Public/public-rdf-star/2020Dec/0076.html

**Comment by pchampin** [comment]
This was discussed during today's call: https://w3c.github.io/rdf-star/Minutes/2020-12-18.html#item04

**Comment by TallTed** [comment]
Seems that distinction should be made between blank node `[]` and blank nodes like `_:a`, as the former are treated as different nodes at each occurrence (even if some or all are externally known to have `owl:sameAs` relations), while the latter are treated as the same node in all occurrences within the same (named) graph and/or within the same Turtle/N3 document.  We cannot speak simply of "blank nodes".

**Comment by TallTed** [comment]
Also, in [today's minutes](https://w3c.github.io/rdf-star/Minutes/2020-12-18.html#item04) --
> <pfps> Well, there is nowhere the triple with subject :a, as triples can't have CURIES as subjects.

What forbids CURIES as subjects?

So far as I'm aware, CURIES (or more likely to be accurate in this context, prefixed names) are simply shorthand for URI/URL/IRIs, and as such are valid RDF (and RDF*) subjects.

What am I missing?

**Comment by pfps** [comment]
Neither [] nor _:a are blank nodes.   The latter is a blank node label and the former is ANON, both part of the Turtle syntax.  Processing Turtle into RDF graphs turns both of them into blank nodes, of course, and in different ways.

**Comment by pfps** [comment]
From RDF 1.1 Concepts and Abstract Syntax:

An RDF triple consists of three components:

    the subject, which is an IRI or a blank node
    the predicate, which is an IRI
    the object, which is an IRI, a literal or a blank node

Things like :a are not even actually CURIES in Turtle, it seems, but are instead prefixed names.  In either case :a is not an IRI.  It is, of course, turned into an IRI when processing Turtle documents.

**Comment by TallTed** [comment]
Right. CURIES (and prefixed names) are elements of serializations (such as Turtle and Turtle*), which are transformed into the IRIs they represent when those serializations are loaded into an RDF or RDF* triple/quad store, because neither CURIES nor prefixed names exist as such in RDF.  (Of course, both may be stored as typed literals (though not typed as IRIs), but then they are permitted only as Objects in most ["ungeneralized"] RDF stores, and as Subjects or Objects in "generalized RDF" stores.)

And in those serializations where they are elements, CURIES and prefixed names are (at least typically) allowed anywhere an IRI is permitted in the abstract RDF, because they are _syntactic sugar_ in the syntax of those serializations of the abstract RDF.

-----

We're in challenging territory here, constantly flitting between the abstract and the material, nearly always expressing the former through/with/as the latter, and frequently blurring the lines of what is acceptable where.

None of these mean quite the same thing as any of the others —

* `<< :a :b :c >>` 
* ` < :a :b :c > ` 
* ` { :a :b :c } `
* `   :a :b :c   `

— (not only because the `:` presumably-prefix is frequently left undefined) but they are all-too-frequently treated as if they do, whether by accident (such as an error in message markup) or on purpose (presumably because of some misunderstanding).

We must all make extreme efforts (including reviewing how our posts and comments look in the various places they go [e.g., email, github conversation threads, git "source" files], and editing where necessary) to correct the accidents, such that we can discover and correct the misunderstandings, including our own as well as others'.

**Comment by pchampin** [comment]
I believe that this is covered by the current version of the semantics (merged from #88).

@pfps do you agree that this issue can be closed?

**Comment by pchampin** [comment]
@pfps I have updated the updated the discussions about the seminal example per your suggestion above.
Do you think that this issue can now be closed?

**Comment by TallTed** [comment]
> I would expect that people coming to the WG first get acquainted with our CG-report.

Based on past experience with others, and my own past activity, I think that is an expectation doomed to disappointment.

I think that incorporating the key decisions highlighted by @pfps (and any others that occur to us) especially in the introductory section of the CG report(s) *and* the WG output(s) is a good plan.

**Comment by matentzn** [comment]
FWIW, going after the cursory readings of blog posts and initial docs, I assumed that embedded triples are unique, just because an LPG can have the same relation multiple times and I thought RDF-Star was supposed to bridge that gap. Just imagine a KG with the elements "user, clicks_on, button", it seems super odd that I cannot simply express multiple clicks (with different timestamps, clique-type, click-strength etc) in a single RDF-Star document. Also, if we integrate data from various sources, it would have been very useful to use flat provenance (:source, :accessed) rather than push the reification we so desperately hoped to avoid somewhere else. I do trust you of course that that design decision is well-thought through, but I agree that the documentation needs to address that misconception head-on, and explain the rationale very clearly. Maybe consider a blog post or something.

**Comment by pchampin** [comment]
> > I would expect that people coming to the WG first get acquainted with our CG-report.
> 
> Based on past experience with others, and my own past activity, I think that is an expectation doomed to disappointment.

I know that. My point was: we shouldn't be blamed (or blame ourselves) if other people are not doing the right thing.

That being said, I also agree that having a section in the intro, to debunk a few misconception (about uniqueness, and about referencial opacity as suggested in #219) would be valuable. Any PR would be welcome :)

**Comment by pchampin** [comment]
this was discussed during today's meeting: https://w3c.github.io/rdf-star/Minutes/2021-11-12.html#t04

**Comment by pchampin** [comment]
Closing as the discussion is continued on #225.
